### ISSUE TITLE
这个仓库还能正常使用吗？

### ISSUE THREAD

**Issue by chudongvip** [Poohl/joycontrol#15]
我的环境是：

Nintendo Switch: 14.0.0

PC: 
- MacOS + Parallels Desktop 16.1.2 +(Ubuntu 19.10 / Ubuntu 20.04.4)
- MacOS + VMware 12.1.1 + Ubuntu 20.04.4

都无法正常工作，这困扰我好几天了。如果作者用时间的话，我真的需要帮助！

**Comment by chudongvip** [comment]
```
chudong@cchudong-virtual-machine:~/chudong/nintendo/newJoycontrol$ sudo python3 run_controller_cli.py PRO_CONTROLLER
too many SPD-records active, Switch might refuse connection.
try modifieing /lib/systemd/system/bluetooth.service and see
https://github.com/Poohl/joycontrol/issues/4 if it doesn't work
[14:25:45] joycontrol.server create_hid_server::80 WARNING - [Errno 98] Address already in use
[14:25:45] joycontrol.server create_hid_server::82 WARNING - Fallback: Restarting bluetooth due to incompatibilities with the bluez "input" plugin. Disable the plugin to avoid issues. See https://github.com/mart1nro/joycontrol/issues/8.
[14:25:45] joycontrol.server create_hid_server::87 INFO - Restarting bluetooth service...
[14:25:45] joycontrol.utils run_system_command::75 DEBUG - ['systemctl restart bluetooth.service' exited with 0]
Traceback (most recent call last):
  File "/home/cchudong/chudong/nintendo/newJoycontrol/joycontrol/server.py", line 77, in create_hid_server
    ctl_sock.bind((bt_addr, ctl_psm))
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_controller_cli.py", line 357, in <module>
    loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "run_controller_cli.py", line 311, in _main
    transport, protocol = await create_hid_server(factory, reconnect_bt_addr=args.reconnect_bt_addr,
  File "/home/cchudong/chudong/nintendo/newJoycontrol/joycontrol/server.py", line 92, in create_hid_server
    ctl_sock.bind((bt_addr, ctl_psm))
OSError: [Errno 98] Address already in use
```

**Comment by a1w5afe** [comment]
我是在更改手柄那里，终端代码不动了就很烦

**Comment by cesar0** [comment]
@chudongvip 我也遇到无法使用的问题, 请问你能正常测试使用这个仓库了吗?

**Comment by UnbalancedCat** [comment]
可以使用！！我今天用树莓派运行成功了。
你这个问题是 #4。去修改一下文件就行了。

**Comment by chudongvip** [comment]
> @chudongvip 我也遇到无法使用的问题, 请问你能正常测试使用这个仓库了吗?
我没运行起来，我说Mac电脑，其他环境没有设备去验证。🥺

**Comment by chudongvip** [comment]
> 可以使用！！我今天用树莓派运行成功了。 你这个问题是 #4。去修改一下文件就行了。

可以无限 amibo 是吧

**Comment by UnbalancedCat** [comment]
> > 可以使用！！我今天用树莓派运行成功了。 你这个问题是 #4。去修改一下文件就行了。
> 
> 可以无限 amibo 是吧
是的
