### ISSUE TITLE
Amiibo usage on 14.1.1 fails - "Connect a controller that can read amiibo"

### ISSUE THREAD

**Issue by EggEngineer** [Poohl/joycontrol#18]
`[22:21:56] joycontrol.transport read::94 ERROR - No data received.
[22:21:56] joycontrol.protocol connection_lost::262 ERROR - Connection lost.
[22:21:56] joycontrol.transport pause_writing::198 INFO - pause transport write
[22:21:56] asyncio default_exception_handler::1744 ERROR - Task exception was never retrieved
future: <Task finished name='Task-1754' coro=<L2CAP_Transport.close() done, defined at /home/zebes/joycontrol/joycontrol/transport.py:208> exception=OSError(107, 'Transport endpoint is not connected')>
Traceback (most recent call last):
  File "/home/zebes/joycontrol/joycontrol/transport.py", line 224, in close
    await self._read_thread
  File "/home/zebes/joycontrol/joycontrol/transport.py", line 78, in _reader
    await self._protocol.report_received(await self.read(), self._itr_sock.getpeername())
OSError: [Errno 107] Transport endpoint is not connected
[22:21:56] asyncio default_exception_handler::1744 ERROR - Exception in callback create_error_check_callback.<locals>.callback(<Task finishe...t connected')>) at /home/zebes/joycontrol/joycontrol/utils.py:55
handle: <Handle create_error_check_callback.<locals>.callback(<Task finishe...t connected')>) at /home/zebes/joycontrol/joycontrol/utils.py:55>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/zebes/joycontrol/joycontrol/utils.py", line 58, in callback
    future.result()
  File "/home/zebes/joycontrol/joycontrol/transport.py", line 224, in close
    await self._read_thread
  File "/home/zebes/joycontrol/joycontrol/transport.py", line 78, in _reader
    await self._protocol.report_received(await self.read(), self._itr_sock.getpeername())
OSError: [Errno 107] Transport endpoint is not connected
[22:21:56] joycontrol.protocol _writer::190 WARNING - Writer exited...`

Seems when I use an aamiibo on AC:NH via this, it tells me "connect a controller that can read amiibo please" on the switch itself... Is there something in the newer firmwares preventing me from using amiibo via this?

**Comment by DJaySaint** [comment]
I am also getting an issue where trying to use Amiibo fails. I've tried Breath of the Wild and a few other games. Input commands work fine and I can navigate menus. I can load NFC data when connecting the controller. As soon as I go to activate the Amiibo, joycontrol stops functioning and the Switch either says "can't read Amiibo" or "connect a controller that can read Amiibo". I'm wondering if it has something to do with the new firmware at this point?

**Comment by Francescde** [comment]
I run into a similar problem writing my own script, the problem was that i was using "time.sleep" to avoid sending too much comands at once, instead i use "await asyncio.sleep(0.5)" and now it works fine

**Comment by xxrei** [comment]
Same issue here, I also have the issue of disconnecting as soon as the change grip/order screen is exited, which I've circumvented by reconnecting at the home screen instead. 
Control inputs work fine, just disconnects once the switch asks me to use a controller that is amiibo-compatible and the grip screen pops up. I know it's been a year, just wanted to chime in that it's a persistent issue!
