### ISSUE TITLE
Issue with libhidapi-libusb.so

### ISSUE THREAD

**Issue by wispii** [Poohl/joycontrol#23]
Been trying to use joycontrol on my linux PC, but I keep encountering this Issue

Traceback (most recent call last):
  File "./run_controller_cli.py", line 10, in <module>
    from joycontrol import logging_default as log, utils
  File "/home/z-r1nwoomy/joycontrol/joycontrol/utils.py", line 5, in <module>
    import hid
  File "/usr/local/lib/python3.8/dist-packages/hid/__init__.py", line 83, in <module>
    hidapi.hid_get_input_report.argtypes = [ctypes.c_void_p, ctypes.c_char_p, ctypes.c_size_t]
  File "/usr/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libhidapi-libusb.so: undefined symbol: hid_get_input_report

I have tried re-installing all the modules needed, as well as building hidapi manually, but nothing has helped.

**Comment by darrenchang** [comment]
Hi, please give this solution a try.
https://github.com/Poohl/joycontrol/issues/17#issuecomment-1140315862

**Comment by darrenchang** [comment]
This issue is a duplicate of https://github.com/Poohl/joycontrol/issues/17#issue-1213491745

**Comment by wispii** [comment]
> Hi, please give this solution a try. [#17 (comment)](https://github.com/Poohl/joycontrol/issues/17#issuecomment-1140315862)

I've tried the soluton, but now i'm getting this error:
Traceback (most recent call last):
  File "./run_controller_cli.py", line 10, in <module>
    from joycontrol import logging_default as log, utils
  File "/home/z-r1nwoomy/joycontrol/joycontrol/utils.py", line 5, in <module>
    import hid
  File "/usr/local/lib/python3.8/dist-packages/hid/__init__.py", line 30, in <module>
    raise ImportError(error)
ImportError: Unable to load any of the following libraries:libhidapi-hidraw.so libhidapi-hidraw.so.0 libhidapi-libusb.so libhidapi-libusb.so.0 libhidapi-iohidmanager.so libhidapi-iohidmanager.so.0 libhidapi.dylib hidapi.dll libhidapi-0.dll

**Comment by darrenchang** [comment]
> 
What is your OS version?

**Comment by wispii** [comment]
> > 
> 
> What is your OS version?

Linux Mint 20.3

**Comment by darrenchang** [comment]
Did you make sure to move your compiled `libhidapi-hidraw.so.0` to
`/usr/lib/arm-linux-gnueabihf/libhidapi-hidraw.so.0`?
And make sure you change the architecture. Mine is arm-linux. yours might my `x86_64_<something>`

**Comment by wispii** [comment]
Yeah, I made sure it was X86_64-linux-gnu when doing the copy commands.

**Comment by darrenchang** [comment]
That's strange. Do you have a raspberry pi that you try this on? I'm using pi 3 and it works flawless. I have to compile my own libhidapi-hidraw.so.0 on pi 3 as well.

**Comment by wispii** [comment]
Sadly no.
