### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by NexusSfan** [Poohl/joycontrol#33]
I ALWAYS GET THE ERROR
`OSError: [Errno 98] Address already in use`

I am on Linux Mint Vera, and bdaddr is not installed and the I can't find the package.
No matter what I do, I ALWAYS get that error. I cannot fix it.

**Comment by NexusSfan** [comment]
Full error:

```
Traceback (most recent call last):
  File "/home/*********/joycontrol/joycontrol/server.py", line 77, in create_hid_server
    ctl_sock.bind((bt_addr, ctl_psm))
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/*********/joycontrol/./run_controller_cli.py", line 357, in <module>
    loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/*********/joycontrol/./run_controller_cli.py", line 311, in _main
    transport, protocol = await create_hid_server(factory, reconnect_bt_addr=args.reconnect_bt_addr,
  File "/home/*********/joycontrol/joycontrol/server.py", line 92, in create_hid_server
    ctl_sock.bind((bt_addr, ctl_psm))
OSError: [Errno 98] Address already in use
```

(yes, the username is censored)

**Comment by skunkmommy** [comment]
Bump

**Comment by NexusSfan** [comment]
nvm, found fix
